name: GitHub integration test
on: [push]
env:
  NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
jobs:
  test-neon-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Call Neon API
        run: |
          echo -n $NEON_API_KEY | base64
          curl 'https://console.neon.tech/api/v2/projects' -H 'Accept: application/json' -H "Authorization: Bearer $NEON_API_KEY"  -H 'Content-Type: application/json' -v

